spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:222/main
    username: root
    password: senha01
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
